'use client';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
const colors = ['#173d35','#ad8a50','#889e93','#b5bcb3'];
// Needs/wants/savings keep the same tones used everywhere else in the app (see
// money-flow.tsx) so the same bucket always reads as the same color.
const bucketColors: Record<string, string> = { Needs: '#173d35', Wants: '#ad8a50', Savings: '#889e93' };
type ChartPoint = { name: string; value: number };
const colorFor = (name: string, index: number) => bucketColors[name] ?? colors[index % colors.length];
const percentOf = (value: number, points: ChartPoint[]) => { const total = points.reduce((sum, point) => sum + point.value, 0); return total > 0 ? Math.round((value / total) * 100) : 0; };
export function SpendCharts({ active = 'Needs', top = [], detail = [], total = 0 }: { active?: string; top?: ChartPoint[]; detail?: ChartPoint[]; total?: number }) { return <div className="space-y-10"><div><div className="mb-3 flex justify-between"><span className="label">Total spend</span><span className="serif text-2xl">${total.toLocaleString()}</span></div><div className="h-56"><ResponsiveContainer><PieChart><Pie data={top} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{top.map((x,i)=><Cell key={x.name} fill={colorFor(x.name,i)} />)}</Pie><Tooltip formatter={(v, n) => [`$${Number(v).toLocaleString()} (${percentOf(Number(v), top)}%)`, n]} /></PieChart></ResponsiveContainer></div><div className="flex flex-wrap justify-center gap-x-6 gap-y-2">{top.map((x,i)=><span key={x.name} className="flex items-center gap-2 text-sm"><i className="inline-block h-2.5 w-2.5 rounded-full" style={{background:colorFor(x.name,i)}} /><span className="font-semibold">{x.name}</span><span className="text-ink/50">{percentOf(x.value, top)}%</span></span>)}</div></div><div><span className="label">{active} breakdown</span><div className="h-56"><ResponsiveContainer><PieChart><Pie data={detail} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={3}>{detail.map((x,i)=><Cell key={x.name} fill={colorFor(x.name,i)} />)}</Pie><Tooltip formatter={(v) => `$${Number(v).toLocaleString()}`} /></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-xs">{detail.map((x,i)=><span key={x.name}><i className="mr-1 inline-block h-2 w-2 rounded-full" style={{background:colorFor(x.name,i)}} />{x.name}</span>)}</div></div></div>; }
