'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { useRouter } from 'next/navigation';

export default function LoginPage() {
  const [error, setError] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [mfaCode, setMfaCode] = useState('');
  const [challengeState, setChallengeState] = useState<{ factorId: string; challengeId: string } | null>(null);
  const router = useRouter();
  const supabase = createClient();
  async function signIn(event: FormEvent) { event.preventDefault(); setError(''); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { setError(error.message); return; } const { data: assurance } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel(); if (assurance?.nextLevel === 'aal2' && assurance.currentLevel !== 'aal2') { const { data: factors } = await supabase.auth.mfa.listFactors(); const factor = factors?.totp?.find(item => item.status === 'verified'); if (!factor) { setError('Your account requires MFA, but no verified authenticator was found.'); return; } const challenge = await supabase.auth.mfa.challenge({ factorId: factor.id }); if (challenge.error || !challenge.data) { setError(challenge.error?.message ?? 'Could not start the authenticator challenge.'); return; } setChallengeState({ factorId: factor.id, challengeId: challenge.data.id }); return; } router.push('/budget'); router.refresh(); }
  async function verifyMfa(event: FormEvent) { event.preventDefault(); if (!challengeState) return; setError(''); const { error } = await supabase.auth.mfa.verify({ factorId: challengeState.factorId, challengeId: challengeState.challengeId, code: mfaCode }); if (error) { setError(error.message); return; } router.push('/budget'); router.refresh(); }
  return <main className="flex min-h-screen items-center justify-center px-6"><section className="w-full max-w-md"><p className="label mb-5">Private household office</p><h1 className="serif text-5xl leading-none">Welcome back.</h1><p className="mt-5 text-sm leading-6 text-ink/60">A quiet place to see the whole picture.</p>{challengeState ? <form onSubmit={verifyMfa} className="mt-12 space-y-5"><div><p className="label">Authenticator required</p><p className="mt-3 text-sm leading-6 text-ink/60">Enter the 6-digit code from your authenticator app to continue.</p></div><label className="block"><span className="label">Verification code</span><input required autoFocus inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={mfaCode} onChange={event => setMfaCode(event.target.value)} className="mt-2 w-full border-b hairline bg-transparent px-0 py-3 tracking-[.3em] outline-none focus:border-forest" /></label>{error && <p className="text-sm text-red-700">{error}</p>}<button className="button-primary mt-3 w-full">Verify and continue</button></form> : <form onSubmit={signIn} className="mt-12 space-y-5"><label className="block"><span className="label">Email</span><input name="email" type="email" required value={email} onChange={event => setEmail(event.target.value)} className="mt-2 w-full border-b hairline bg-transparent px-0 py-3 outline-none focus:border-forest" /></label><label className="block"><span className="label">Password</span><input name="password" type="password" required value={password} onChange={event => setPassword(event.target.value)} className="mt-2 w-full border-b hairline bg-transparent px-0 py-3 outline-none focus:border-forest" /></label>{error && <p className="text-sm text-red-700">{error}</p>}<button className="button-primary mt-3 w-full">Sign in</button></form>}</section></main>;
}
