'use client';
import { FormEvent, useState } from 'react';

type FutureExpense = { id: number; name: string; amount: number; target: string; source: string; note: string };
const initialExpenses: FutureExpense[] = [{ id: 1, name: 'Couch', amount: 2000, target: 'September 2026', source: 'HYSA', note: 'For the new house' }];

export function FutureExpensesView() {
  const [expenses, setExpenses] = useState(initialExpenses);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState({ name: '', amount: '', target: '', source: 'HYSA', note: '' });
  const reset = () => { setForm({ name: '', amount: '', target: '', source: 'HYSA', note: '' }); setEditingId(null); setShowForm(false); };
  const submit = (event: FormEvent) => { event.preventDefault(); const item = { id: editingId ?? Date.now(), name: form.name, amount: Number(form.amount), target: form.target, source: form.source, note: form.note }; setExpenses(items => editingId ? items.map(existing => existing.id === editingId ? item : existing) : [...items, item]); reset(); };
  const edit = (expense: FutureExpense) => { setEditingId(expense.id); setForm({ name: expense.name, amount: String(expense.amount), target: expense.target, source: expense.source, note: expense.note }); setShowForm(true); };
  return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-10"><div className="mb-10 flex items-end justify-between"><div><p className="label mb-3">Household office · Planning</p><h1 className="serif text-5xl">Future Expenses</h1><p className="mt-4 max-w-xl text-sm leading-6 text-ink/60">A simple forward view of large purchases and the account you intend to use for them.</p></div><button aria-label="Add future expense" onClick={() => setShowForm(true)} className="flex h-12 w-12 items-center justify-center rounded-full bg-forest text-2xl font-light text-white transition hover:bg-ink">+</button></div>
    {showForm && <form onSubmit={submit} className="mb-10 border-y hairline py-8"><div className="mb-6 flex items-center justify-between"><div><p className="label">{editingId ? 'Edit expense' : 'New future expense'}</p><h2 className="serif mt-1 text-2xl">Plan the purchase</h2></div><button type="button" onClick={reset} className="text-xs uppercase tracking-wider text-ink/45">Cancel</button></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><label className="block"><span className="label">What</span><input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Couch" className="mt-2 w-full border-b hairline bg-transparent py-2 outline-none focus:border-forest" /></label><label className="block"><span className="label">Amount</span><input required min="0" step="0.01" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} placeholder="2000" className="mt-2 w-full border-b hairline bg-transparent py-2 outline-none focus:border-forest" /></label><label className="block"><span className="label">When</span><input required type="month" value={form.target} onChange={e => setForm({ ...form, target: e.target.value })} className="mt-2 w-full border-b hairline bg-transparent py-2 outline-none focus:border-forest" /></label><label className="block"><span className="label">Use funds from</span><select value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} className="mt-2 w-full border-b hairline bg-transparent py-2 outline-none focus:border-forest"><option>HYSA</option><option>Joint checking</option><option>Alston's Wants</option><option>Wife's Wants</option><option>Fidelity</option></select></label></div><label className="mt-5 block md:max-w-xl"><span className="label">Note</span><input value={form.note} onChange={e => setForm({ ...form, note: e.target.value })} placeholder="For the new house" className="mt-2 w-full border-b hairline bg-transparent py-2 outline-none focus:border-forest" /></label><button className="button-primary mt-7">{editingId ? 'Save changes' : 'Add expense'}</button></form>}
    {expenses.length === 0 ? <div className="border-t hairline py-16 text-center text-sm text-ink/50">No future expenses planned yet. Use the plus sign to add one.</div> : <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{expenses.map(expense => <article key={expense.id} className="border hairline bg-white/30 p-6"><div className="flex items-start justify-between"><div><p className="label">{expense.target ? new Date(`${expense.target}-01T12:00:00`).toLocaleDateString(undefined, { month: 'long', year: 'numeric' }) : 'No date'}</p><h2 className="serif mt-2 text-3xl">{expense.name}</h2></div><button onClick={() => { if (window.confirm('Delete this future expense?')) setExpenses(items => items.filter(item => item.id !== expense.id)); }} aria-label={`Delete ${expense.name}`} className="text-lg text-ink/35 hover:text-red-700">×</button></div><p className="serif mt-8 text-4xl text-forest">${expense.amount.toLocaleString()}</p><div className="mt-6 border-t hairline pt-4 text-sm"><p className="label">Funding source</p><p className="mt-1">{expense.source}</p>{expense.note && <p className="mt-4 text-ink/55">{expense.note}</p>}</div><button onClick={() => edit(expense)} className="mt-6 text-xs uppercase tracking-[.16em] text-gold">Edit expense →</button></article>)}</div>}
    <p className="mt-10 text-xs text-ink/40">Demo mode: these plans are stored in this page’s local state until Supabase persistence is connected.</p>
  </main>;
}
